shellEmulator: true

trustPolicy: no-downgrade

packages:
  - apps/*
  - docs
  - internal/*
  - internal/lint-configs/*
  - playground
  - packages/*

catalogs:
  cli:
    '@changesets/cli': ^2.29.8
    '@types/node': ^24.10.1
    fast-glob: ^3.3.3
    lefthook: ^2.0.16
    typescript: ~5.9.0
  docs:
    '@nolebase/vitepress-plugin-enhanced-readabilities': ^2.18.2
    '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
    '@nolebase/vitepress-plugin-git-changelog/client': ^2.18.2
    '@shikijs/vitepress-twoslash': ^3.22.0
    '@vitepress-demo-preview/component': ^2.6.1
    '@vitepress-demo-preview/core': ^0.3.0
    '@vitepress-demo-preview/plugin': ^1.4.1
    vitepress: 2.0.0-alpha.16
    vitepress-sidebar: ^1.33.1
  lint-format:
    '@antfu/eslint-config': ^7.2.0
    '@changesets/changelog-github': 0.5.2
    '@commitlint/cli': 20.4.1
    '@commitlint/config-conventional': 20.4.1
    '@vue-vine/eslint-config': 1.1.12
    czg: ^1.12.0
    eslint: ^9.39.2
    eslint-plugin-oxlint: 1.43.0
    globals: 17.3.0
    lint-staged: ^16.2.7
    oxlint: 1.43.0
  style:
    tailwindcss: ^4.2.0
  vite:
    '@iconify/json': ^2.2.443
    '@tailwindcss/vite': ^4.2.0
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.4
    unplugin-auto-import: ^21.0.0
    unplugin-element-plus: ^0.11.2
    unplugin-icons: ^23.0.1
    unplugin-turbo-console: 2.3.0
    unplugin-vue-components: ^31.0.0
    vite: ^7.3.0
  vue:
    '@element-plus/icons-vue': ^2.3.2
    '@vue/tsconfig': ^0.8.1
    element-plus: ^2.13.1
    portal-vue: ^3.0.0
    vue: ^3.5.25
    # vue-router: ^4.6.3
    vue-vine: ^1.7.27
    vue-vine-tsc: ^1.7.27

ignoredBuiltDependencies:
  - less
  - vue-demi

onlyBuiltDependencies:
  - lefthook
