/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
}